#!/bin/sh

user="${S_USER:-root}"
pass="${S_PASS:-root}"
port="${S_PORT:-4700}"
host="${S_HOST:-127.0.0.1}"
method="${S_METHOD:-}"
dbpath="${S_DBPATH:-database}"
loglevel="${S_LOGLEVEL:-debug}"

if [ -n "$dbpath" ]; then
  method="file://$dbpath"
fi

echo "Starting SurrealDB server with:"
echo "  Username: $user"
echo "  Password: $pass"
echo "  Host: $host"
echo "  Port: $port"
echo "  Method: $method"
echo "  Log level: $loglevel"
echo ""

surreal start "$method" -A --username "$user" --password "$pass" --bind "$host":"$port" --log "$loglevel" "$@"
