#!/bin/sh

user="${DATABASE_USER:-root}"
pass="${DATABASE_PASS:-root}"
port="${DATABASE_PORT:-4700}"
host="${DATABASE_HOST:-127.0.0.1}"
method="${DATABASE_METHOD:-}"
dbpath="${DATABASE_DBPATH:-database}"
loglevel="${DATABASE_LOGLEVEL:-debug}"

if [ -n "$dbpath" ]; then
  method="file://$dbpath"
fi

echo "Starting SurrealDB server with:"
echo "  Username: $user"
echo "  Password: $pass"
echo "  Host: $host"
echo "  Port: $port"
echo "  Method: $method"
echo "  Log level: $loglevel"
echo "  Database path: $dbpath"
echo ""

surreal start "$method" -A --username "$user" --password "$pass" --bind "$host":"$port" --log "$loglevel" "$@"
